import "@/styles/globals.css";

import { Kanit } from "next/font/google";
import { ChakraUIProviders } from "./providers/ChakraProvider";

const kanit = Kanit({
  weight: ["300"],
  style: "normal",
  subsets: ["latin"],
});

export const metadata = {
  title: "RCS",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <ChakraUIProviders>{children}</ChakraUIProviders>
      </body>
    </html>
  );
}
